### ISSUE TITLE
text color 

### ISSUE THREAD

**Issue by adamitu5** [fyshbowl/fyshbowl.github.io#1]
Can the text be changed to black? It's hard to read.

**Comment by bayer4** [comment]
the fyshbowl.co text?

**Comment by bayer4** [comment]
![screen shot 2015-03-16 at 12 47 17 pm](https://cloud.githubusercontent.com/assets/11480715/6672486/d4e45c12-cbda-11e4-947c-d70eb2b0ad68.png)
![screen shot 2015-03-16 at 12 48 03 pm](https://cloud.githubusercontent.com/assets/11480715/6672487/d50bfac4-cbda-11e4-9bb6-2b44a7b9b681.png)

**Comment by adamitu5** [comment]
much better imo
